### ISSUE TITLE
BIMSurfer connects but UI fails to load after login.

### ISSUE THREAD

**Issue by MartinOrdinateur** [opensourceBIM/BIMsurfer-before2019#94]
Greetings. 

I'm trying to run the twin install of BIMserver and BIMsurfer but although I have the server up and running, the -surfer shows a login prompt and connects after login, but then loads the screen shown in the attached image. 
![screenshot](https://cloud.githubusercontent.com/assets/7139508/2592068/c8e48bd8-ba71-11e3-8651-4b3ae9b6bd03.png)

Starting the server, I get the following log from the BIMServer starter: 

```
No expanding necessary
Windows 7
Main class: org.bimserver.JarBimServer
Running: java -Xmx8551m -Xss1024k -XX:MaxPermSize=256m -classpath lib;lib\activation.jar;lib\antlr-2.7.7.jar;lib\antlr-3.1.1-runtime.jar;lib\antlr-3.1.1.jar;lib\aopalliance-1.0.jar;lib\asm-3.3.1.jar;lib\bimserver-2013-09-09.00-02-31-client-lib.jar;lib\bimserver-2013-09-09.00-02-31-ifc.jar;lib\bimserver-2013-09-09.00-02-31-shared.jar;lib\bimserver-2013-09-09.00-02-31-utils.jar;lib\bimserver-2013-09-09.00-02-31-xsltserializer.jar;lib\bimserver-2013-09-09.00-02-31.jar;lib\catalina.jar;lib\classmexer.jar;lib\commons-beanutils-1.8.3.jar;lib\commons-beanutils-bean-collections-1.8.3.jar;lib\commons-beanutils-core-1.8.3.jar;lib\commons-codec-1.3.jar;lib\commons-codec-1.7.jar;lib\commons-collections-3.2.1.jar;lib\commons-fileupload-1.2.1.jar;lib\commons-io-1.4.jar;lib\commons-lang-2.4.jar;lib\commons-lang-2.6.jar;lib\commons-logging-1.1.1.jar;lib\commons-pool-1.5.2.jar;lib\cors-filter-1.5.jar;lib\cxf-2.7.3.jar;lib\cxf-manifest.jar;lib\cxf-services-sts-core-2.7.3.jar;lib\cxf-services-ws-discovery-api-2.7.3.jar;lib\cxf-services-ws-discovery-service-2.7.3.jar;lib\cxf-services-wsn-api-2.7.3.jar;lib\cxf-services-wsn-core-2.7.3.jar;lib\cxf-xjc-boolean-2.6.1.jar;lib\cxf-xjc-bug671-2.6.1.jar;lib\cxf-xjc-dv-2.6.1.jar;lib\cxf-xjc-runtime-2.6.1.jar;lib\cxf-xjc-ts-2.6.1.jar;lib\ehcache-core-2.5.1.jar;lib\FastInfoset-1.2.12.jar;lib\geoapi-2.3-M1.jar;lib\geoapi-pending-2.3-M1.jar;lib\geronimo-javamail_1.4_spec-1.7.1.jar;lib\geronimo-jaxws_2.2_spec-1.1.jar;lib\geronimo-jms_1.1_spec-1.1.1.jar;lib\gson-2.2.4.jar;lib\guava-13.0.1.jar;lib\guice-2.0.jar;lib\httpasyncclient-4.0-beta3.jar;lib\httpclient-4.2.1.jar;lib\httpcore-4.2.2.jar;lib\httpcore-nio-4.2.2.jar;lib\httpmime-4.2.2.jar;lib\ifcNamespaces.jar;lib\isorelax-20030108.jar;lib\java-getopt-1.0.13.jar;lib\javassist.jar;lib\javax.ws.rs-api-2.0-m10.jar;lib\jaxb-api-2.2.6.jar;lib\jaxb-impl-2.2.6.jar;lib\jaxb-xjc-2.2.6.jar;lib\jdom-1.0.jar;lib\je-5.0.73.jar;lib\jettison-1.3.3.jar;lib\jetty-ajp-8.1.9.v20130131.jar;lib\jetty-annotations-8.1.9.v20130131.jar;lib\jetty-client-8.1.9.v20130131.jar;lib\jetty-continuation-8.1.9.v20130131.jar;lib\jetty-deploy-8.1.9.v20130131.jar;lib\jetty-http-8.1.9.v20130131.jar;lib\jetty-io-8.1.9.v20130131.jar;lib\jetty-jmx-8.1.9.v20130131.jar;lib\jetty-jndi-8.1.9.v20130131.jar;lib\jetty-overlay-deployer-8.1.9.v20130131.jar;lib\jetty-plus-8.1.9.v20130131.jar;lib\jetty-policy-8.1.9.v20130131.jar;lib\jetty-rewrite-8.1.9.v20130131.jar;lib\jetty-security-8.1.9.v20130131.jar;lib\jetty-server-8.1.9.v20130131.jar;lib\jetty-servlet-8.1.9.v20130131.jar;lib\jetty-servlets-8.1.9.v20130131.jar;lib\jetty-util-8.1.9.v20130131.jar;lib\jetty-webapp-8.1.9.v20130131.jar;lib\jetty-websocket-8.1.9.v20130131.jar;lib\jetty-xml-8.1.9.v20130131.jar;lib\jna.jar;lib\joda-time-1.6.2.jar;lib\joda-time-1.6.jar;lib\JOpenId-1.08.jar;lib\js-1.7R2.jar;lib\jsr173_1.0_api.jar;lib\junit-4.8.2.jar;lib\log4j-1.2.16.jar;lib\log4j.xml;lib\mail.jar;lib\mina-core-2.0.5.jar;lib\msv-core-2011.1.jar;lib\neethi-3.0.2.jar;lib\nekohtml-1.9.14.jar;lib\oauth-20100527.jar;lib\oauth-provider-20100527.jar;lib\openid4java-0.9.8.jar;lib\openmali.jar;lib\opensaml-2.5.1-1.jar;lib\openws-1.4.2-1.jar;lib\org.eclipse.core.contenttype_3.4.200.v20120523-2004.jar;lib\org.eclipse.core.jobs_3.5.200.v20120521-2346.jar;lib\org.eclipse.core.resources_3.8.0.v20120522-2034.jar;lib\org.eclipse.core.runtime_3.8.0.v20120521-2346.jar;lib\org.eclipse.emf.codegen.ecore_2.8.2.v20130125-0826.jar;lib\org.eclipse.emf.codegen_2.8.0.v20130125-0826.jar;lib\org.eclipse.emf.common_2.8.0.v20130125-0546.jar;lib\org.eclipse.emf.ecore.xmi_2.8.1.v20130125-0546.jar;lib\org.eclipse.emf.ecore_2.8.3.v20130125-0546.jar;lib\org.eclipse.emf_2.6.0.v20130125-0826.jar;lib\org.eclipse.equinox.common_3.6.100.v20120522-1841.jar;lib\org.eclipse.equinox.preferences_3.5.0.v20120522-1841.jar;lib\org.eclipse.jdt.core_3.8.1.v20120531-0637.jar;lib\org.eclipse.osgi_3.8.0.v20120529-1548.jar;lib\protocolbuffers2.5.jar;lib\quartz-1.8.3.jar;lib\relaxngDatatype-20020414.jar;lib\resolver.jar;lib\rome-1.0.jar;lib\servlet-api-3.0.jar;lib\slf4j-api-1.6.2.jar;lib\slf4j-log4j12-1.6.2.jar;lib\spring-aop-3.0.7.RELEASE.jar;lib\spring-asm-3.0.7.RELEASE.jar;lib\spring-beans-3.0.7.RELEASE.jar;lib\spring-context-3.0.7.RELEASE.jar;lib\spring-core-3.0.7.RELEASE.jar;lib\spring-expression-3.0.7.RELEASE.jar;lib\spring-jms-3.0.7.RELEASE.jar;lib\spring-tx-3.0.7.RELEASE.jar;lib\spring-web-3.0.7.RELEASE.jar;lib\stax2-api-3.1.1.jar;lib\stringtemplate-3.2.jar;lib\tar.jar;lib\tomcat-coyote.jar;lib\tomcat-juli.jar;lib\tomcat-util.jar;lib\velocity-1.7.jar;lib\woodstox-core-asl-4.1.4.jar;lib\wsdl4j-1.6.2.jar;lib\wss4j-1.6.9.jar;lib\xbean.jar;lib\xbean_xpath.jar;lib\xercesImpl-2.8.1.jar;lib\xml-resolver-1.2.jar;lib\xmlbeans-2.6.0.jar;lib\xmlbeans-qname.jar;lib\xmlpublic.jar;lib\xmlschema-core-2.0.3.jar;lib\xmlsec-1.5.3.jar;lib\xmltooling-1.3.2-1.jar;lib\xsdlib-2010.1.jar org.bimserver.JarBimServer address=localhost port=8082 homedir="D:\data\mst20548\Downloads\servers\BIMserver\BIMserver-nightly\home"
Logging to: D:\data\mst20548\Downloads\servers\BIMserver\BIMserver-nightly\home\logs\bimserver.log
02-04-2014 16:15:38 INFO  org.bimserver.BimServer - Starting BIMserver
02-04-2014 16:15:38 INFO  org.bimserver.BimServer - Using "D:\data\mst20548\Downloads\servers\BIMserver\BIMserver-nightly\home" as homedir
02-04-2014 16:15:40 DEBUG org.bimserver.BimServer - SServiceMap Created
02-04-2014 16:15:40 DEBUG org.bimserver.BimServer - JsonSocketReflectorFactory created
02-04-2014 16:15:41 DEBUG org.bimserver.BimServer - ServerInfoManager created
02-04-2014 16:15:41 DEBUG org.bimserver.BimServer - NotificationsManager created
02-04-2014 16:15:41 DEBUG org.bimserver.BimServer - InternalServicesManager created
02-04-2014 16:15:41 DEBUG org.bimserver.BimServer - PublicInterfaceFactory created
02-04-2014 16:15:41 DEBUG org.bimserver.BimServer - PluginManager created
02-04-2014 16:15:41 DEBUG org.bimserver.BimServer - Version Checker created
02-04-2014 16:15:41 DEBUG org.bimserver.BimServer - Compare cache created
02-04-2014 16:15:41 DEBUG org.bimserver.BimServer - Embedded webserver created
02-04-2014 16:15:41 DEBUG org.bimserver.BimServer - Done with initial setup
02-04-2014 16:15:41 DEBUG org.bimserver.JarBimServer - Settings resourcebase to www
02-04-2014 16:15:41 DEBUG org.bimserver.JarBimServer - Loading plugins
02-04-2014 16:15:41 DEBUG org.bimserver.plugins.PluginManager - Loading all plugins from D:\data\mst20548\Downloads\servers\BIMserver\BIMserver-nightly\bimserver-2013-09-09.00-02-31\plugins
02-04-2014 16:15:41 DEBUG org.bimserver.plugins.PluginManager - Loading plugins from D:\data\mst20548\Downloads\servers\BIMserver\BIMserver-nightly\bimserver-2013-09-09.00-02-31\plugins\admingui2013-07-12.jar
02-04-2014 16:15:41 DEBUG org.bimserver.plugins.PluginManager - Loading plugin AdminWebModulePlugin of type WebModulePlugin
02-04-2014 16:15:41 DEBUG org.bimserver.plugins.PluginManager - Loading plugins from D:\data\mst20548\Downloads\servers\BIMserver\BIMserver-nightly\bimserver-2013-09-09.00-02-31\plugins\bimql2013-04-22.jar
02-04-2014 16:15:42 DEBUG org.bimserver.plugins.PluginManager - Loading plugin BimQLQueryEnginePlugin of type QueryEnginePlugin
02-04-2014 16:15:43 DEBUG org.bimserver.plugins.PluginManager - Loading plugins from D:\data\mst20548\Downloads\servers\BIMserver\BIMserver-nightly\bimserver-2013-09-09.00-02-31\plugins\bimserver-2013-09-09.00-02-31-buildingSMARTLibrary.jar
02-04-2014 16:15:43 DEBUG org.bimserver.plugins.PluginManager - Loading plugin BuildingSmartLibrarySchemaPlugin of type SchemaPlugin
02-04-2014 16:15:43 DEBUG org.bimserver.plugins.PluginManager - Loading plugins from D:\data\mst20548\Downloads\servers\BIMserver\BIMserver-nightly\bimserver-2013-09-09.00-02-31\plugins\bimserver-2013-09-09.00-02-31-citygml.jar
02-04-2014 16:15:43 DEBUG org.bimserver.plugins.PluginManager - Loading plugin CityGmlSerializerPlugin of type SerializerPlugin
02-04-2014 16:15:44 DEBUG org.bimserver.plugins.PluginManager - Loading plugins from D:\data\mst20548\Downloads\servers\BIMserver\BIMserver-nightly\bimserver-2013-09-09.00-02-31\plugins\bimserver-2013-09-09.00-02-31-collada.jar
02-04-2014 16:15:44 DEBUG org.bimserver.plugins.PluginManager - Loading plugin ColladaSerializerPlugin of type SerializerPlugin
02-04-2014 16:15:44 DEBUG org.bimserver.plugins.PluginManager - Loading plugins from D:\data\mst20548\Downloads\servers\BIMserver\BIMserver-nightly\bimserver-2013-09-09.00-02-31\plugins\bimserver-2013-09-09.00-02-31-filebasedobjectidm.jar
02-04-2014 16:15:44 DEBUG org.bimserver.plugins.PluginManager - Loading plugin FileBasedObjectIDMPlugin of type ObjectIDMPlugin
02-04-2014 16:15:44 DEBUG org.bimserver.plugins.PluginManager - Loading plugins from D:\data\mst20548\Downloads\servers\BIMserver\BIMserver-nightly\bimserver-2013-09-09.00-02-31\plugins\bimserver-2013-09-09.00-02-31-ifcengine.jar
02-04-2014 16:15:44 DEBUG org.bimserver.plugins.PluginManager - Loading plugin TNOJvmRenderEnginePlugin of type RenderEnginePlugin
02-04-2014 16:15:45 DEBUG org.bimserver.plugins.PluginManager - Loading plugins from D:\data\mst20548\Downloads\servers\BIMserver\BIMserver-nightly\bimserver-2013-09-09.00-02-31\plugins\bimserver-2013-09-09.00-02-31-ifcplugins.jar
02-04-2014 16:15:45 DEBUG org.bimserver.plugins.PluginManager - Loading plugin JsonSerializerPlugin of type SerializerPlugin
02-04-2014 16:15:45 DEBUG org.bimserver.plugins.PluginManager - Loading plugin IfcStepSerializerPlugin of type SerializerPlugin
02-04-2014 16:15:45 DEBUG org.bimserver.plugins.PluginManager - Loading plugin IfcXmlSerializerPlugin of type SerializerPlugin
02-04-2014 16:15:45 DEBUG org.bimserver.plugins.PluginManager - Loading plugin IfcXmlDeserializerPlugin of type DeserializerPlugin
02-04-2014 16:15:45 DEBUG org.bimserver.plugins.PluginManager - Loading plugin IfcStepDeserializerPlugin of type DeserializerPlugin
02-04-2014 16:15:45 DEBUG org.bimserver.plugins.PluginManager - Loading plugin NameBasedModelComparePlugin of type ModelComparePlugin
02-04-2014 16:15:45 DEBUG org.bimserver.plugins.PluginManager - Loading plugin GuidBasedModelComparePlugin of type ModelComparePlugin
02-04-2014 16:15:45 DEBUG org.bimserver.plugins.PluginManager - Loading plugins from D:\data\mst20548\Downloads\servers\BIMserver\BIMserver-nightly\bimserver-2013-09-09.00-02-31\plugins\bimserver-2013-09-09.00-02-31-javaqueryengine.jar
02-04-2014 16:15:45 DEBUG org.bimserver.plugins.PluginManager - Loading plugin JavaQueryEnginePlugin of type QueryEnginePlugin
02-04-2014 16:15:45 DEBUG org.bimserver.plugins.PluginManager - Loading plugins from D:\data\mst20548\Downloads\servers\BIMserver\BIMserver-nightly\bimserver-2013-09-09.00-02-31\plugins\bimserver-2013-09-09.00-02-31-mergers.jar
02-04-2014 16:15:45 DEBUG org.bimserver.plugins.PluginManager - Loading plugin IntelligentNameBasedModelMergerPlugin of type ModelMergerPlugin
02-04-2014 16:15:45 DEBUG org.bimserver.plugins.PluginManager - Loading plugin IntelligentGuidBasedModelMergerPlugin of type ModelMergerPlugin
02-04-2014 16:15:45 DEBUG org.bimserver.plugins.PluginManager - Loading plugin BasicModelMergerPlugin of type ModelMergerPlugin
02-04-2014 16:15:45 DEBUG org.bimserver.plugins.PluginManager - Loading plugins from D:\data\mst20548\Downloads\servers\BIMserver\BIMserver-nightly\bimserver-2013-09-09.00-02-31\plugins\bimserver-2013-09-09.00-02-31-miscserializers.jar
02-04-2014 16:15:45 DEBUG org.bimserver.plugins.PluginManager - Loading plugin ObjectInfoSerializerPlugin of type SerializerPlugin
02-04-2014 16:15:45 DEBUG org.bimserver.plugins.PluginManager - Loading plugins from D:\data\mst20548\Downloads\servers\BIMserver\BIMserver-nightly\bimserver-2013-09-09.00-02-31\plugins\bimserver-2013-09-09.00-02-31-scenejs.jar
02-04-2014 16:15:45 DEBUG org.bimserver.plugins.PluginManager - Loading plugin JsonGeometrySerializerPlugin of type SerializerPlugin
02-04-2014 16:15:45 DEBUG org.bimserver.plugins.PluginManager - Loading plugin SceneJsShellSerializerPlugin of type SerializerPlugin
02-04-2014 16:15:45 DEBUG org.bimserver.plugins.PluginManager - Loading plugins from D:\data\mst20548\Downloads\servers\BIMserver\BIMserver-nightly\bimserver-2013-09-09.00-02-31\plugins\ifcopenshell20130603.jar
02-04-2014 16:15:52 DEBUG org.bimserver.plugins.PluginManager - Loading plugin IfcOpenShellEnginePlugin of type RenderEnginePlugin
02-04-2014 16:15:53 DEBUG org.bimserver.BimServer - Starting BIMserver
02-04-2014 16:15:53 INFO  org.bimserver.BimServer - Version: 1.2.0 - null
02-04-2014 16:15:53 DEBUG org.bimserver.plugins.PluginManager - Loading plugin SchemaFieldObjectIDMPlugin of type ObjectIDMPlugin
02-04-2014 16:15:53 DEBUG org.bimserver.plugins.PluginManager - Loading plugin DefaultWebModulePlugin of type WebModulePlugin
02-04-2014 16:15:53 DEBUG org.bimserver.plugins.PluginManager - Loading plugin GuidFixerService of type ServicePlugin
02-04-2014 16:15:53 DEBUG org.bimserver.plugins.PluginManager - Initializig all loaded plugins
02-04-2014 16:15:54 INFO  nl.tue.buildingsmart.emf.BuildingSmartLibrarySchemaPlugin - IFC-Schema successfully loaded from D:\data\mst20548\Downloads\servers\BIMserver\BIMserver-nightly\home\tmp\IFC2X3_TC1.exp
02-04-2014 16:15:57 INFO  org.ifcopenshell.IfcOpenShellEnginePlugin - Using lib/64/IfcJni.dll
02-04-2014 16:15:57 INFO  org.bimserver.templating.TemplateEngine - Using "D:\data\mst20548\Downloads\servers\BIMserver\BIMserver-nightly\bimserver-2013-09-09.00-02-31\home\templates\" as template dir
02-04-2014 16:15:57 DEBUG velocity - Log4JLogChute using logger 'velocity'
02-04-2014 16:15:57 DEBUG velocity - Initializing Velocity, Calling init()...
02-04-2014 16:15:57 DEBUG velocity - Starting Apache Velocity v1.7 (compiled: 2010-11-19 12:14:37)
02-04-2014 16:15:57 DEBUG velocity - Default Properties File: org\apache\velocity\runtime\defaults\velocity.properties
02-04-2014 16:15:57 DEBUG velocity - Trying to use logger class org.apache.velocity.runtime.log.Log4JLogChute
02-04-2014 16:15:57 DEBUG velocity - Using logger class org.apache.velocity.runtime.log.Log4JLogChute
02-04-2014 16:15:57 DEBUG velocity - ResourceLoader instantiated: org.apache.velocity.runtime.resource.loader.URLResourceLoader
02-04-2014 16:15:57 DEBUG velocity - URLResourceLoader : adding root 'file:/D:/data/mst20548/Downloads/servers/BIMserver/BIMserver-nightly/bimserver-2013-09-09.00-02-31/home/templates/'
02-04-2014 16:15:57 DEBUG velocity - ResourceCache: initialized (class org.apache.velocity.runtime.resource.ResourceCacheImpl) with class java.util.Collections$SynchronizedMap cache map.
02-04-2014 16:15:57 DEBUG velocity - Loaded System Directive: org.apache.velocity.runtime.directive.Stop
02-04-2014 16:15:57 DEBUG velocity - Loaded System Directive: org.apache.velocity.runtime.directive.Define
02-04-2014 16:15:57 DEBUG velocity - Loaded System Directive: org.apache.velocity.runtime.directive.Break
02-04-2014 16:15:57 DEBUG velocity - Loaded System Directive: org.apache.velocity.runtime.directive.Evaluate
02-04-2014 16:15:57 DEBUG velocity - Loaded System Directive: org.apache.velocity.runtime.directive.Literal
02-04-2014 16:15:57 DEBUG velocity - Loaded System Directive: org.apache.velocity.runtime.directive.Macro
02-04-2014 16:15:57 DEBUG velocity - Loaded System Directive: org.apache.velocity.runtime.directive.Parse
02-04-2014 16:15:57 DEBUG velocity - Loaded System Directive: org.apache.velocity.runtime.directive.Include
02-04-2014 16:15:57 DEBUG velocity - Loaded System Directive: org.apache.velocity.runtime.directive.Foreach
02-04-2014 16:15:57 DEBUG velocity - Created '20' parsers.
02-04-2014 16:15:57 DEBUG velocity - Velocimacro : "velocimacro.library" is not set.  Trying default library: VM_global_library.vm
02-04-2014 16:15:57 DEBUG velocity - URLResourceLoader: Exception when looking for 'VM_global_library.vm' at 'file:/D:/data/mst20548/Downloads/servers/BIMserver/BIMserver-nightly/bimserver-2013-09-09.00-02-31/home/templates/'
java.io.FileNotFoundException: D:\data\mst20548\Downloads\servers\BIMserver\BIMserver-nightly\bimserver-2013-09-09.00-02-31\home\templates\VM_global_library.vm (Het systeem kan het opgegeven bestand niet vinden)
    at java.io.FileInputStream.open(Native Method)
    at java.io.FileInputStream.<init>(Unknown Source)
    at java.io.FileInputStream.<init>(Unknown Source)
    at sun.net.www.protocol.file.FileURLConnection.connect(Unknown Source)
    at sun.net.www.protocol.file.FileURLConnection.getInputStream(Unknown Source)
    at org.apache.velocity.runtime.resource.loader.URLResourceLoader.getResourceStream(URLResourceLoader.java:115)
    at org.apache.velocity.runtime.resource.loader.ResourceLoader.resourceExists(ResourceLoader.java:224)
    at org.apache.velocity.runtime.resource.ResourceManagerImpl.getLoaderForResource(ResourceManagerImpl.java:629)
    at org.apache.velocity.runtime.resource.ResourceManagerImpl.getLoaderNameForResource(ResourceManagerImpl.java:612)
    at org.apache.velocity.runtime.RuntimeInstance.getLoaderNameForResource(RuntimeInstance.java:1595)
    at org.apache.velocity.runtime.VelocimacroFactory.initVelocimacro(VelocimacroFactory.java:159)
    at org.apache.velocity.runtime.RuntimeInstance.init(RuntimeInstance.java:274)
    at org.apache.velocity.app.VelocityEngine.init(VelocityEngine.java:93)
    at org.bimserver.templating.TemplateEngine.init(TemplateEngine.java:76)
    at org.bimserver.BimServer.start(BimServer.java:334)
    at org.bimserver.JarBimServer.start(JarBimServer.java:84)
    at org.bimserver.JarBimServer.main(JarBimServer.java:53)
02-04-2014 16:15:57 DEBUG velocity - Could not load resource 'VM_global_library.vm' from ResourceLoader org.apache.velocity.runtime.resource.loader.URLResourceLoader: D:\data\mst20548\Downloads\servers\BIMserver\BIMserver-nightly\bimserver-2013-09-09.00-02-31\home\templates\VM_global_library.vm (Het systeem kan het opgegeven bestand niet vinden)
02-04-2014 16:15:57 DEBUG velocity - Velocimacro : Default library not found.
02-04-2014 16:15:57 DEBUG velocity - Velocimacro : allowInline = true : VMs can be defined inline in templates
02-04-2014 16:15:57 DEBUG velocity - Velocimacro : allowInlineToOverride = false : VMs defined inline may NOT replace previous VM definitions
02-04-2014 16:15:57 DEBUG velocity - Velocimacro : allowInlineLocal = false : VMs defined inline will be global in scope if allowed.
02-04-2014 16:15:57 DEBUG velocity - Velocimacro : autoload off : VM system will not automatically reload global library macros
02-04-2014 16:15:57 INFO  org.bimserver.database.berkeley.BerkeleyKeyValueStore - Non-empty database directory found "D:\data\mst20548\Downloads\servers\BIMserver\BIMserver-nightly\home\database"
02-04-2014 16:15:58 INFO  org.bimserver.ServerInfoManager - Changing server state to RUNNING
02-04-2014 16:16:07 INFO  org.bimserver.JarBimServer - Server started successfully
02-04-2014 16:16:41 ERROR org.bimserver.servlets.JsonApiServlet - Invalid JSON request: 
02-04-2014 16:16:41 ERROR org.bimserver.servlets.JsonApiServlet - Invalid JSON request: 
02-04-2014 16:16:41 ERROR org.bimserver.servlets.JsonApiServlet - Invalid JSON request: 
02-04-2014 16:16:41 ERROR org.bimserver.servlets.JsonApiServlet - Invalid JSON request: 
```

As you can see at the beginning, the server has already been configured and since stopped and started. The short stacktraces in the debug worry me slightly, but it doesn't seem to interrupt the workings of the server.. 

The last for lines: "02-04-2014 16:16:41 ERROR org.bimserver.servlets.JsonApiServlet - Invalid JSON request: " Appear when I try to login with a BIMsurfer. 

The BIMSurfer version is the most recent version from github. 
The BIMserver version is the last known nightly build. The reason I'm using the nightly build is because although I can build the latest version of the Server, running it I end up with the stacktrace: 

```
Logging to: D:\data\mst20548\workspace\BIMserver\BimServer\home\logs\bimserver.log
16:40:10 INFO  Starting BIMserver                                                               (org.bimserver.BimServer.java:216) 
16:40:10 INFO  Using "D:\data\mst20548\workspace\BIMserver\BimServer\home" as homedir           (org.bimserver.BimServer.java:218) 
16:40:13 ERROR                                                                                  (org.bimserver.BimServer.java:259) 
java.lang.IllegalArgumentException: url parameter must not be null
    at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(Unknown Source)
    at org.bimserver.version.VersionChecker.<init>(VersionChecker.java:67)
    at org.bimserver.BimServer.<init>(BimServer.java:244)
    at org.bimserver.JarBimServer.start(JarBimServer.java:78)
    at org.bimserver.JarBimServer.main(JarBimServer.java:53)
16:40:17 ERROR                                                                                  (org.bimserver.JarBimServer.java:87) 
java.lang.NullPointerException
    at org.bimserver.JarBimServer.start(JarBimServer.java:81)
    at org.bimserver.JarBimServer.main(JarBimServer.java:53)
```

My closest guess, is that the latest version of BIMSurfer is not compatible with BIMServer 1.2. Either that, or the most recent version of the surfer / server is somehow broken. 

Hope to hear from you. 

Kind regards,

Martin.

**Comment by dlabz** [comment]
You are right, latest BIMSurfer requires the latest build of BIMServer. 

Cheers

**Comment by arshpreetsingh** [comment]
I am having the same error. I am using BIMserver 1.3.0 and BIMsufer version 3.0. Please tell me which versions are compatible with each other.

**Comment by berlotti** [comment]
BIM Surfer is not an end-user tool anymore, but a framework for developers to build their own viewer. Please use www.bimvie.ws when you want an end-user tool.

**Comment by ulrick** [comment]
Any documentation for the BIMsurfer Framework?
